// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20pzNvopOH3yEw8GEBQHUvQFOUo06nKI',
    appId: '1:767232279794:android:f3ab7d1ee1bb5d4d3c3c6b',
    messagingSenderId: '767232279794',
    projectId: 'meca-app-2025',
    databaseURL: 'https://meca-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'meca-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPTUKg8WhqdoR7sWooJIBysXGr398A_A',
    appId: '1:767232279794:ios:c0d548d371e9cf673c3c6b',
    messagingSenderId: '767232279794',
    projectId: 'meca-app-2025',
    databaseURL: 'https://meca-app-2025-default-rtdb.firebaseio.com',
    storageBucket: 'meca-app-2025.firebasestorage.app',
    iosBundleId: 'br.com.megaleios.mecaOficina',
  );
}
